Interactive List: Add Drag and Drop
francisuloko/to-do-list pull request #3
Opened 2021-07-16 08:54 UTC by francisuloko

Summary:

1. Added a sorted drag and drop functionality to task item

2021-07-16 10:41 UTC, Davidosky007 requested changes
Hi @francisuloko, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
* Some of the project requirements are not been implemented, i left you highlighted links of the requirements which are missing below kindly make the necessary adjustments 🙏 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-16 10:41 UTC, Davidosky007 commented on README.md
> +- Added dragged and drop functionality to To-Do list
* Kindly make your README file more descriptive by adding proper instructions on how to set up and run your project locally. it helps visitors of your repo understand how to run your project locally

2021-07-16 10:41 UTC, Davidosky007 commented on src/index.js
> +import Task from './task.js';
* As stated in the [Project Requirement](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m2_interactive_list.md#:~:text=Add%202%20new,completed%3A%20true%20/%20false) a module should be imported for handling status update eg: (completed: true/false).

2021-07-16 10:41 UTC, Davidosky007 commented on src/drag-and-drop.js
> +    dropped.addEventListener('drop', drop, false);
* I suggest you create a default list of Todos so that these EventListeners can be carried out on

2021-07-16 10:41 UTC, Davidosky007 commented on src/index.js
> +    description.value = '';
* Kindly implement [These Functionalities ](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m2_interactive_list.md#:~:text=Add%202%20new,the%20page%20reloads.)as currently none of them is working 🙏

2021-07-16 18:37 UTC, Temmarie requested changes
## STATUS: CHANGES REQUIRED! :recycle:

### Hi @francisuloko    ! :wave: :wave:

#### You have done really well in implementing the previously required changes.
 However, there are changes required for you to make in order for this project to be approved. 
- - -

### **Required Changes** ♻️

_See the inline comments below for more required changes_


### Optional Changes 👌
Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend that you take them into account as they can make your code better.
- N/A

_If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below_

**_"Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."_**
- - - 
**Note that you still have 1 more review as written in the [Code Reviews Limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561), however, if you feel this review is unfair, you can request a second opinion using [this](https://airtable.com/shrQAqnBwek5a0O0s) form.**

__Kindly make the necessary changes and submit another code review request.__

2021-07-16 18:37 UTC, Temmarie commented on src/drag-and-drop.js
> +  for (let i = 0; i < tasks.length; i += 1) {
- [ ] As requested by the previous reviewer, kindly implement the drag and drop functionality. It still doesn't work.

2021-07-16 20:19 UTC, Spayco reviewed
Hello 👋,

_This is an additional review as a result of the second opinion request._

The drag and drop still doesn't work on my end, when i try to drag, i can see the text next to the cursor, but moving it around doesn't replace its index, please fix it

![Animation](https://user-images.githubusercontent.com/11758151/126004138-934a2c40-c409-4a5a-9abe-154be5c59223.gif)


Keep rocking 🚀!

2021-07-17 17:36 UTC, smcommits approved these changes
### Status: Approved 👍🏽 

Hi @francisuloko, 

## You have done a great job! Your project is complete. This PR is now approved. You can go ahead and merge the branch. Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-07-17 18:26 UTC, francisuloko commented
Hi guys, Thank you so much for reviewing and approving my code; I learnt so much today trying to make things work. Happy Coding :computer:
 @Davidosky007 @Temmarie @Spayco @smcommits

2021-07-17 18:26 UTC, merged